// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjednhdqdyisacgzyrhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqZWRuaGRxZHlpc2FjZ3p5cmhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzEzMDcsImV4cCI6MjA2NzQ0NzMwN30.6QLtqYFM-yvRZjVCkb6hxd3eISs_PA5gNwk-Tv6sqKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});